### ISSUE TITLE
搜索栏无法跳出，右侧栏点击标签没有收回展开效果

### ISSUE THREAD

**Issue by Hxppdv** [Hanccc/typecho_material_theme#11]
一直无法解决 求解

**Comment by Hanson** [comment]
不太清楚你说的是什么情况，你可以看看我的有没有你说的 http://www.hanc.cc/
或者贴上你自己博客链接方便查问题

**Comment by Maskrighter** [comment]
@Hanccc 我看过了，你的站并没有这个问题。我的博客：http://blog.maskrighter.com

**Comment by Hanson** [comment]
经查看发现你没有引入任何输入此主题的JS，看看自己是否改动过，footer.php文件是否包含下面代码
`

<script src="<?php $this->options->themeUrl('js/jquery-2.1.4.min.js'); ?>"></script>

```
<script src="<?php $this->options->themeUrl('js/bootstrap.min.js'); ?>"></script>
<script src="<?php $this->options->themeUrl('js/material.min.js'); ?>"></script>
<script src="<?php $this->options->themeUrl('js/ripples.min.js'); ?>"></script>
```

`

**Comment by Hxppdv** [comment]
我看看。

**Comment by Hxppdv** [comment]
@Hanccc 这些代码我都有，自己也从未做过改动，但为何会出现这种情况。

**Comment by Hanson** [comment]
你是整个footer.php文件都没有引入，请仔细查看 index.php 是否含有
`<?php $this->need('footer.php'); ?>`

**Comment by Hxppdv** [comment]
@Hanccc index.php里面有这行代码，我是直接下载并上传到服务器的，我一下午也排除了各种可能，但仍是不知道为何会出现这种情况。

**Comment by Hanson** [comment]
开启php错误提示，有可能是缺少拓展导致php报错，停止执行下面的代码了
