### ISSUE TITLE
关于主题头部的图片

### ISSUE THREAD

**Issue by Latezly** [Hanccc/typecho_material_theme#15]
作者你好，我弄了一个php脚本用于自动获取pixiv排名第一的图片，想让这个主题的头部图片指向这个php文件，能请问一下关于这个在哪改嘛？

**Comment by Hanson** [comment]
index.php 有个 section 标签用了 billboard 的类
自行修改CSS即可

css/customs.css `.billboard{background:#b8d9fa url(../img/billboard.jpg)`

**Comment by vazyine** [comment]
好的，非常感谢(｡･ω･｡)ﾉ♡

**Comment by Latezly** [comment]
好的 非常感谢(｡･ω･｡)ﾉ♡
