### ISSUE TITLE
关于导航栏显示

### ISSUE THREAD

**Issue by xlzd** [Hanccc/typecho_material_theme#3]
你好,请问导航栏目前会显示全部分类(包括二级分类), 而且并不会按照分类的层级显示,请问有办法修改吗?

**Comment by Hanson** [comment]
有是有，但这个暂时不在修改计划中

**Comment by xlzd** [comment]
另外"显示归档"会导致页面结构变乱?

**Comment by Hanson** [comment]
不会，请确保没有修改插件哦

**Comment by xlzd** [comment]
好的,谢谢~

**Comment by Hanson** [comment]
还有你可以关注我刚刚新建的项目，是对于Material Theme的友情链接插件

**Comment by Hanson** [comment]
时隔半年，二级分类已经增加了
