### ISSUE TITLE
没有标签的时候显示bug

### ISSUE THREAD

**Issue by Sunappnio** [Hanccc/typecho_material_theme#5]
如图，有标签的时候恢复。
![screenshot 2015-12-17 at 16 35 12](https://cloud.githubusercontent.com/assets/13669701/11865020/34a78fae-a4dc-11e5-8672-74862bdaab41.png)

**Comment by Sunappnio** [comment]
另外500 database query error的问题，解决方法需要将主题文件夹的名字改掉。
默认从github下载的zip，解压后文件夹名字带特殊字符所以不行。

**Comment by Hanson** [comment]
谢谢提醒了，描述的问题也将在新版本修复

**Comment by simonsmh** [comment]
_临时删除sidebar.php的48或49行的</div>（误）_
这个并不是迷一样的bug的解决方法是把sidebar.php的48行移动到44-45行之间，以抵消无内容的tags_box。
@Hanccc 请务必把项目名中的-换成_ ，对clone和pull都有好处，不需要再更主题文件夹名字了，多谢！

**Comment by Hanson** [comment]
好的，谢谢你的意见
