### ISSUE TITLE
在移动设备端Footer过长超出容器

### ISSUE THREAD

**Issue by EAimTY** [Hanccc/typecho_material_theme#7]
在移动设备端Footer过长超出容器
如图，望修复
![eg](https://cloud.githubusercontent.com/assets/13065214/12219781/22f1e436-b78c-11e5-8cb9-606dbab93556.png)

**Comment by Hanson** [comment]
好的，谢谢提出，现在已修改好并更新了

**Comment by EAimTY** [comment]
但是这样改动后，主题信息、和备案号，也就是超出的那一部分无法显示了

**Comment by Hanson** [comment]
个人觉得手机端也没有必要去展示这些信息，而且加上版权信息就4条信息比较难摆放，隐藏是暂时比较好的解决方案了，如果你有更好的欢迎提出
