### ISSUE TITLE
More分割线无法正常工作

### ISSUE THREAD

**Issue by simonsmh** [Hanccc/typecho_material_theme#8]
More分割线无法正常工作?

**Comment by Hanson** [comment]
我刚测试了一下是可以的，你可以看看我的，http://hanc.cc ，你看看是否使用了其他插件所导致，这个主题没有改动编辑器以及文章显示的问题，所以具体还需要你自己去排查一下

**Comment by simonsmh** [comment]
作者使用的是什么版本的typecho？

**Comment by Hanson** [comment]
1.0 (14.10.10)
